### ISSUE TITLE
[BUG] ItemFrame

### ISSUE THREAD

**Issue by SMarc1** [WasteLand-Dev/CraftableInvFrames#1]
**Describe the bug**
When removing the back block with the invisible frame, the block disappears.

**Video**
https://youtu.be/wE9sk3PpFyQ

**Desktop (please complete the following information):**
This server is running Pufferfish version git-Pufferfish-60 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 52307ae on HEAD)
You are on the latest version!
Previous version: git-Pufferfish-59 (MC: 1.19.3)

**Comment by SpiritOTHawk** [comment]
I will test and try to fix it in a short free time, if you have your own solution to the problem, you can open a pool request

**Comment by SMarc1** [comment]
Okay, I'll wait for the fix
