### ISSUE TITLE
Add console for get command

### ISSUE THREAD

**Issue by NoltoxGit** [WasteLand-Dev/CraftableInvFrames#3]
**Is your feature request related to a problem? Please describe.**
I want to make a `/blocks` menu for my Creative server, but I can't give the frame inivisible unless I give them permission but I don't want that.

**Describe the solution you'd like**
Would it be possible that the command `/craftableinvframes:iframe get` could be executed in the console with the indication of a player: `/craftableinvframes:iframe get Noltox` for example.

**Describe alternatives you've considered**
Potentially give the player permission to do this command. But I don't want to.

Thank you for your plugin,
~ Noltox ~

**Comment by SpiritOTHawk** [comment]
Created give command
Use /iframe give <player>
